import { Router } from 'express';
import newsRoutes from './news';
import healthRoutes from './health';
import adminNewsRoutes from './admin/news';
import adminMonitorRoutes from './admin/monitor';
import adminConfigRoutes from './admin/config';
import adminAnalyticsRoutes from './admin/analytics';
import adminClusterRoutes from './admin/cluster';
import adminRssRoutes from './admin/rss';
import adminAlertsRoutes from './admin/alerts';
import adminSlaRoutes from './admin/sla';
import adminJobsRoutes from './admin/jobs';
import adminTokensRoutes from './admin/tokens';
import adminSecurityRoutes from './admin/security';
import adminAuditRoutes from './admin/audit';
import adminNerRoutes from './admin/ner';
import adminMonitoringRoutes from './admin/monitoring';
import adminApiKeysRoutes from './admin/api-keys';
import adminTelegramRoutes from './admin/telegram';
import adminYoutubeRoutes from './admin/youtube';
import adminUserTokensRoutes from './admin/user-tokens';
import adminAdminChannelsRoutes from './admin/admin-channels';
import myRoutes from './my';
import weatherRoutes from './weather';
import adminWeatherRoutes from './admin/weather';
import pushRoutes from './push';
import eventsRoutes from './events';
import rssRoutes from './rss';
import telegramRoutes from './telegram';
import youtubeRoutes from './youtube';
import contactRoutes from './contact';

const router = Router();

router.use('/weather', weatherRoutes);
router.use('/admin/weather', adminWeatherRoutes);
router.use('/news', newsRoutes);
router.use('/telegram', telegramRoutes);
router.use('/youtube', youtubeRoutes);
router.use('/my', myRoutes);
router.use('/rss', rssRoutes);
router.use('/health', healthRoutes);
router.use('/push', pushRoutes);
router.use('/events', eventsRoutes);
router.use('/contact', contactRoutes);
router.use('/admin/news', adminNewsRoutes);
router.use('/admin/monitor', adminMonitorRoutes);
router.use('/admin/config', adminConfigRoutes);
router.use('/admin/analytics', adminAnalyticsRoutes);
router.use('/admin/cluster', adminClusterRoutes);
router.use('/admin/rss', adminRssRoutes);
router.use('/admin/alerts', adminAlertsRoutes);
router.use('/admin/sla', adminSlaRoutes);
router.use('/admin/jobs', adminJobsRoutes);
router.use('/admin/tokens', adminTokensRoutes);
router.use('/admin/security', adminSecurityRoutes);
router.use('/admin/audit', adminAuditRoutes);
router.use('/admin/ner', adminNerRoutes);
router.use('/admin/monitoring', adminMonitoringRoutes);
router.use('/admin/api-keys', adminApiKeysRoutes);
router.use('/admin/telegram', adminTelegramRoutes);
router.use('/admin/youtube', adminYoutubeRoutes);
router.use('/admin/user-tokens', adminUserTokensRoutes);
router.use('/admin/admin-channels', adminAdminChannelsRoutes);

export default router;
